### PR TITLE
specify .nvmrc as 8.11.3 and add comment about tsc target

### PR DESCRIPTION
**Pull request by finnigantime**
- Specify node version as 8.11.3 instead of 8.11. Just having 8.11 and following instructions here led to an error for me:

screen shot 2018-07-17 at 7 49 01 am

- Add a comment about tsc target. For frontend projects, I think we will typically want to target an older es version supported widely by older browsers.

### CODE REVIEW

**Comment by finnigantime** [comment]
not sure why test-style is failing - where to look?

screen shot 2018-07-17 at 8 07 16 am

**Comment by nevir** [comment]
Hmm, this is actually a problem in nacho's scripts/include/node.sh (it's being too strict)

**Comment by nevir** [comment]
re: the style failure; you need to run prettier on tsconfig.json (there's an extra newline at the bottom of the file)

```
yarn fix-style
```

**Comment by finnigantime** [comment]
👍 , closing

**Pull request closed without merging**
